
DEAL::This test has to throw an exception
